### Arithmetic and Broadcasting in NumPy


In [1]:
import numpy as np

#### Basic Arithmetic

In [2]:
# Generate a 3x3 array of random numbers from 0 to 9
x = np.random.randint(0,10,(3,3))


In [3]:
print(x)

[[1 3 5]
 [0 9 4]
 [3 4 3]]


In [4]:
# scalar multiplication

y = x*2
print(y)

[[ 2  6 10]
 [ 0 18  8]
 [ 6  8  6]]


In [7]:
# define a 1x3 array
a = np.array([1,2,3])
print(a.size)
print(a)

3
[1 2 3]


In [8]:
print(a*y)

[[ 2 12 30]
 [ 0 36 24]
 [ 6 16 18]]


In [9]:
c = np.array([[1,2,3]])
print(c)

[[1 2 3]]


In [11]:
print(c.size)

3


In [10]:
print(c*y)

[[ 2 12 30]
 [ 0 36 24]
 [ 6 16 18]]


In [12]:
print(x.shape)
print(y.shape)
print(x+y)

(3, 3)
(3, 3)
[[ 3  9 15]
 [ 0 27 12]
 [ 9 12  9]]


In [13]:
print(x-y)

[[-1 -3 -5]
 [ 0 -9 -4]
 [-3 -4 -3]]


In [14]:
print(y-x)

[[1 3 5]
 [0 9 4]
 [3 4 3]]


In [15]:
b = np.array([2,2])
print(b)

[2 2]


In [16]:
# try to add two arrays of different shapes
print(b + y)


ValueError: operands could not be broadcast together with shapes (2,) (3,3) 